export default [
  {
    source: '天龙八部',
    list: [
      '乔峰',
      '王语嫣',
      '段誉',
      '慕容复',
      '虚竹',
      '阿朱',
      '阿紫',
      '天山童姥',
      '刀白凤',
      '丁春秋',
      '无崖子',
      '云中鹤',
      '叶二娘',
      '李秋水',
      '鸠摩智',
      '段延庆',
      '段正淳',
      '梦姑',
      '游坦之',
      '慕容博',
    ],
  },
  {
    source: '射雕英雄传',
    list: [
      '黄蓉',
      '郭靖',
      '杨康',
      '穆念慈',
      '一灯大师',
      '洪七公',
      '欧阳峰',
      '黄药师',
      '丘处机',
      '王处一',
      '尹志平',
      '华筝',
      '刘瑛姑',
      '朱聪',
      '陈玄风',
      '陆乘风',
      '陆冠英',
      '沙通天',
      '欧阳克',
      '梅超风',
      '铁木真',
      '拖雷',
      '段天德',
      '周伯通',
      '郭啸天',
      '柯镇恶',
      '南希仁',
      '鲁有脚',
      '裘千仞',
      '裘千丈',
      '完颜洪烈',
    ],
  },
  {
    source: '神雕侠侣',
    list:["杨过","小龙女","郭靖","黄蓉","郭芙","郭襄","郭破虏","耶律楚材","耶律晋","耶律齐","耶律燕","武三通","武三娘","武敦儒","武修文","完颜萍","黄药师","欧阳锋","一灯","洪七公","周伯通","瑛姑","裘千仞","裘千尺","公孙止","公孙绿萼","柔儿","樊一翁","金轮国师","尼摩星","尹克西","潇湘子","马光佐","霍都","达尔巴","川边五丑","陆立鼎","陆二娘","陆无双","程英","李莫愁","洪凌波","孙婆婆","朱子柳","泗水渔隐","柯镇恶","陆冠英","程瑶迦","曲傻姑","马钰","刘处玄","丘处机","王处一","郝大通","孙不二","甄志丙","赵志敬","陈志常","鹿清笃","忽必烈","蒙哥","鲁有脚","彭长老","简长老","王重阳","杨康","段智兴","一灯大师","梅超风","黑风双煞","朱聪","韩宝驹","南希人","张阿生","全金发","韩小莹","沈青刚","尹志平","包惜弱","冯衡","术赤","天竺僧人孙不二","札木合"]
  },
  {
    source: '倚天屠龙记',
    list: [
      '张无忌',
      '赵敏',
      '周芷若',
      '宋青书',
      '殷离',
      '宋远桥',
      '俞莲舟',
      '俞岱岩',
      '张松溪',
      '殷梨亭',
      '莫声谷',
      '朱九真',
      '黄衫女子',
      '范遥',
      '谢逊',
      '殷天正',
      '黛绮丝',
      '殷素素',
      '小昭',
      '杨不悔',
      '成昆',
      '张翠山张三丰',
      '常遇春',
      '朱元璋',
      '徐达',
      '韦一笑',
      '陈友谅',
      '杨逍',
      '灭绝师太',
    ],
  },
  {
    source: '甄嬛传',
    list: ["甄嬛","耿月宾","乌拉那拉·宜修","年世兰","沈眉庄","安陵容","温实初","浣碧","朱柔则","朱宜修","齐月宾","冯若昭","徐燕宜","吕盈风","曹琴默","方淳意","慕容世兰","余氏","胡蕴蓉","杜佩筠","黎萦","管文鸳","倪氏","傅如吟","叶澜依","荣赤芍","刘令娴","周佩","赵仙蕙","汪轩瑃","史移芸","杨梦笙","穆景秋","严致秀","罗惜惜","江沁水","祝含芷","陆氏","乔氏","金氏良媛","韦氏才人","丽贵嫔","崔槿汐","余容娘子","更衣","采女","妙音娘子"]
  },
  {
    source: 'Harry Potter',
    lang: 'en',
    list: [
      'Harry Potter',
      'Hermione Granger',
      'Ron Weasley',
      'Albus Dumbledore',
      'Severus Snape',
      'Lord Voldemort',
      'Sirius Black',
      'Rubeus Hagrid',
      'Ginny Weasley',
      'Luna Lovegood',
      'Neville Longbottom',
      'Draco Malfoy',
      'Remus Lupin',
      'Bellatrix Lestrange',
      'Dobby',
      'Minerva McGonagall',
      'Fred Weasley',
      'George Weasley',
      'Molly Weasley',
      'Arthur Weasley',
      'Percy Weasley',
      'Bill Weasley',
      'Fleur Delacour',
      'Cedric Diggory',
      'Cho Chang',
      'Dolores Umbridge',
      'Kreacher',
      'Lucius Malfoy',
      'Narcissa Malfoy',
      'Bellatrix Lestrange',
      'Horace Slughorn',
      'Kingsley Shacklebolt',
      'Nymphadora Tonks',
      'Rita Skeeter',
      'Argus Filch',
      'Moaning Myrtle',
      'Nearly Headless Nick',
      'Cornelius Fudge',
      'Dolohov',
      'Gellert Grindelwald',
      'Alastor Moody',
      'Barty Crouch',
      'Vernon Dursley',
      'Petunia Dursley',
      'Dudley Dursley',
      'Tom Riddle',
      'Katie Bell',
      'Vincent Crabbe',
      'Gregory Goyle',
      'Colin Creevey',
      'Oliver Wood',
      'Cormac McLaggen',
      'Lavender Brown',
      'Parvati Patil',
      'Padma Patil',
      'Dean Thomas',
      'Nigel Wolpert',
      'Susan Bones',
      'Justin Finch-Fletchley',
      'Hannah Abbott',
      'Ernie Macmillan',
      'Zacharias Smith',
      'Cedric Diggory',
    ],
  },
];

export const NicknamePrefix = [
      '牛气哄哄',
      '英俊潇洒',
      '风流倜傥',
      '玉树临风',
      '年少多金',
      '神勇威武',
      '天下无敌',
      '宇内第一',
      '寂寞高手',
      '刀枪不入',
      '唯我独尊',
      '玉面郎君',
      '仁者无敌',
      '勇者无惧',
      '金刚不坏',
      '英明神武',
      '侠义非凡',
      '义薄云天',
      '古往今来',
      '无与伦比',
      '谦虚好学',
      '不耻下问',
      '聪明伶俐',
      '活泼可爱',
      '待友热情',
      '对敌冷酷',
      '阴险狡诈',
      '无所不为',
      '心狠手辣',
      '无恶不作',
      '寿与天齐',
      '百折不饶',
      '百打不死',
      '侠中豪杰',
      '人中龙凤',
      '有情有义',
      '有胆有色',
      '举世无双',
      '既酷又帅',
      '人之表率',
      '诚实可信',
      '谈吐大方',
      '风度翩翩',
      '气势淩人',
      '气质高贵',
      '单身贵族',
      '貌赛潘安',
      '智胜孔明',
      '勇比子龙',
      '义超关羽',
      '巧越鲁班',
      '至尊至圣',
      '至高无上',
      '华丽绚烂',
      '英勇无比',
      '道德榜样',
      '千杯不醉',
      '坐怀不乱',
      '知识渊博',
      '才高八斗',
      '傲视众生',
      '世外高人',
      '光明磊落',
      '公正无私',
      '震古烁今',
      '急如风',
      '静如林',
      '掠如火',
      '不动如山',
];
