export default [
  {
    source: 'Game of Thrones',
    list: [
      'Eddard Stark',
      'Catelyn Stark',
      'Robb Stark',
      'Sansa Stark',
      'Arya Stark',
      'Brandon Stark',
      'Rickon Stark',
      'Jon Snow',
      'Robert Baratheon',
      'Cersei Lannister',
      'Jaime Lannister',
      'Tyrion Lannister',
      'Joffrey Baratheon',
      'Myrcella Baratheon',
      'Tommen Baratheon',
      'Daenerys Targaryen',
      'Viserys Targaryen',
      'Khal Drogo',
      'Petyr Baelish',
      'Varys',
      'Sandor Clegane',
      'Gregor Clegane',
      'Jorah Mormont',
      'Samwell Tarly',
      'Davos Seaworth',
      'Stannis Baratheon',
      'Melisandre',
      'Davos Seaworth',
      'Margaery Tyrell',
      'Olenna Tyrell',
      'Brienne of Tarth',
      'Bronn',
      'Tormund Giantsbane',
      'Theon Greyjoy',
      'Yara Greyjoy',
      'Euron Greyjoy',
      'Ramsay Bolton',
      'Roose Bolton',
      'Gendry',
      "Jaqen H'ghar",
      'High Sparrow',
      'Missandei',
      'Grey Worm',
      'Podrick Payne',
      'Hodor',
    ],
  },
  {
    source: 'Harry Potter',
    list: [
      'Harry Potter',
      'Hermione Granger',
      'Ron Weasley',
      'Albus Dumbledore',
      'Severus Snape',
      'Lord Voldemort',
      'Sirius Black',
      'Rubeus Hagrid',
      'Ginny Weasley',
      'Luna Lovegood',
      'Neville Longbottom',
      'Draco Malfoy',
      'Remus Lupin',
      'Bellatrix Lestrange',
      'Dobby',
      'Minerva McGonagall',
      'Fred Weasley',
      'George Weasley',
      'Molly Weasley',
      'Arthur Weasley',
      'Percy Weasley',
      'Bill Weasley',
      'Fleur Delacour',
      'Cedric Diggory',
      'Cho Chang',
      'Dolores Umbridge',
      'Kreacher',
      'Lucius Malfoy',
      'Narcissa Malfoy',
      'Bellatrix Lestrange',
      'Horace Slughorn',
      'Kingsley Shacklebolt',
      'Nymphadora Tonks',
      'Rita Skeeter',
      'Argus Filch',
      'Moaning Myrtle',
      'Nearly Headless Nick',
      'Cornelius Fudge',
      'Dolohov',
      'Gellert Grindelwald',
      'Alastor Moody',
      'Barty Crouch',
      'Vernon Dursley',
      'Petunia Dursley',
      'Dudley Dursley',
      'Tom Riddle',
      'Katie Bell',
      'Vincent Crabbe',
      'Gregory Goyle',
      'Colin Creevey',
      'Oliver Wood',
      'Cormac McLaggen',
      'Lavender Brown',
      'Parvati Patil',
      'Padma Patil',
      'Dean Thomas',
      'Nigel Wolpert',
      'Susan Bones',
      'Justin Finch-Fletchley',
      'Hannah Abbott',
      'Ernie Macmillan',
      'Zacharias Smith',
      'Cedric Diggory',
    ],
  },
];
